version: "3.7"
services:

  thrift:
    image: godatadriven/spark:2.4.5
    ports:
      - "10000:10000"
      - "4040:4040"
    depends_on:
      - hive-metastore
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server
    volumes:
      - ./.spark-warehouse/:/spark-warehouse/
      - ./docker/hive-site.xml:/usr/spark/conf/hive-site.xml
    environment:
      - WAIT_FOR=hive-metastore:5432

  hive-metastore:
    image: postgres:9.6.17-alpine
    volumes:
      - ./.hive-metastore/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore
